/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HangMan;

import java.awt.Cursor;
import java.util.ArrayList;   //truecrypt
import javax.swing.ImageIcon;
import java.awt.Toolkit;

/**
 *
 * @author Spectra
 */
public class GUIApp extends java.awt.Frame {

    ArrayList<Character> displayedWord = new ArrayList<Character>();
    ArrayList<Character> actualWord = new ArrayList<Character>();
    HangmanPhrase myPhrase = new HangmanPhrase();
    ScoreKeeper score = new ScoreKeeper();
    String category = "Around the House";
    String difficulty = "Easy";

    /**
     * Creates new form MainFrame
     */
    public GUIApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyGroup = new javax.swing.ButtonGroup();
        catagoriesGroup = new javax.swing.ButtonGroup();
        winnerFrame = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        youLoseFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        coverHead = new javax.swing.JLabel();
        coverBody = new javax.swing.JLabel();
        coverRightArm = new javax.swing.JLabel();
        coverLeftArm = new javax.swing.JLabel();
        coverRightLeg = new javax.swing.JLabel();
        coverLeftLeg = new javax.swing.JLabel();
        hangMan = new javax.swing.JLabel();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        wordArea = new javax.swing.JTextArea();
        newWordButton = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        easy = new javax.swing.JRadioButton();
        medium = new javax.swing.JRadioButton();
        hard = new javax.swing.JRadioButton();
        jToolBar2 = new javax.swing.JToolBar();
        house = new javax.swing.JRadioButton();
        movie = new javax.swing.JRadioButton();
        fiction = new javax.swing.JRadioButton();
        rhyme = new javax.swing.JRadioButton();
        tv = new javax.swing.JRadioButton();
        jToolBar3 = new javax.swing.JToolBar();
        statsPane = new javax.swing.JTextPane();

        setBackground(java.awt.Color.black);
        setForeground(java.awt.Color.gray);
        setIconImage(Toolkit.getDefaultToolkit().getImage(GUIApp.class.getResource("/HangMan/Hangman.png")));
        setName(""); // NOI18N
        setResizable(false);
        setTitle("Hangman");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winnerFrame.setVisible(false);
        winnerFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("(>^_^)> WINNER <(^_^<)");
        winnerFrame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        add(winnerFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 610, 230));

        youLoseFrame.setVisible(false);
        youLoseFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("(-_-) YOU LOSE (-_-)");
        youLoseFrame.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 360, 130));

        add(youLoseFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 210));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coverHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/HangmanCover.jpg"))); // NOI18N
        jPanel1.add(coverHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 93, 50, 50));

        coverBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/HangmanCover.jpg"))); // NOI18N
        jPanel1.add(coverBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 143, 10, 100));

        coverRightArm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/HangmanCover.jpg"))); // NOI18N
        jPanel1.add(coverRightArm, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 150, 35, 40));

        coverLeftArm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/HangmanCover.jpg"))); // NOI18N
        jPanel1.add(coverLeftArm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 31, 60));

        coverRightLeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/HangmanCover.jpg"))); // NOI18N
        jPanel1.add(coverRightLeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 235, 40, 60));

        coverLeftLeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/HangmanCover.jpg"))); // NOI18N
        jPanel1.add(coverLeftLeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 235, 50, 50));

        hangMan.setBackground(new java.awt.Color(255, 255, 255));
        hangMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan/Hangman.jpg"))); // NOI18N
        jPanel1.add(hangMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 260));

        aButton.setText("A");
        aButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });
        jPanel1.add(aButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 50, 30));

        bButton.setText("B");
        bButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 50, 30));

        cButton.setText("C");
        cButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 50, 30));

        dButton.setText("D");
        dButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 50, 30));

        eButton.setText("E");
        eButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });
        jPanel1.add(eButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 50, 30));

        fButton.setText("F");
        fButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 50, 30));

        gButton.setText("G");
        gButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 50, 30));

        hButton.setText("H");
        hButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hButtonActionPerformed(evt);
            }
        });
        jPanel1.add(hButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 50, 30));

        iButton.setText("I");
        iButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });
        jPanel1.add(iButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 50, 30));

        jButton.setText("J");
        jButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 50, 30));

        kButton.setText("K");
        kButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonActionPerformed(evt);
            }
        });
        jPanel1.add(kButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 50, 30));

        lButton.setText("L");
        lButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });
        jPanel1.add(lButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 50, 30));

        mButton.setText("M");
        mButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 50, 30));

        nButton.setText("N");
        nButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 50, 30));

        oButton.setText("O");
        oButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        oButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oButtonActionPerformed(evt);
            }
        });
        jPanel1.add(oButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 50, 30));

        pButton.setText("P");
        pButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 50, 30));

        qButton.setText("Q");
        qButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });
        jPanel1.add(qButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 50, 30));

        rButton.setText("R");
        rButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 50, 30));

        sButton.setText("S");
        sButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 50, 30));

        tButton.setText("T");
        tButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 50, 30));

        uButton.setText("U");
        uButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        uButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uButtonActionPerformed(evt);
            }
        });
        jPanel1.add(uButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 50, 30));

        vButton.setText("V");
        vButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonActionPerformed(evt);
            }
        });
        jPanel1.add(vButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 50, 30));

        wButton.setText("W");
        wButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wButtonActionPerformed(evt);
            }
        });
        jPanel1.add(wButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 50, 30));

        xButton.setText("X");
        xButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });
        jPanel1.add(xButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 50, 30));

        yButton.setText("Y");
        yButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        yButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yButtonActionPerformed(evt);
            }
        });
        jPanel1.add(yButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 50, 30));

        zButton.setText("Z");
        zButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        zButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zButtonActionPerformed(evt);
            }
        });
        jPanel1.add(zButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 50, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wordArea.setColumns(20);
        wordArea.setFont(new java.awt.Font("Monospaced", 0, 50)); // NOI18N
        wordArea.setLineWrap(true);
        wordArea.setRows(5);
        wordArea.setWrapStyleWord(true);
        jPanel2.add(wordArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 250));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 720, 250));

        newWordButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        newWordButton.setText("Start");
        newWordButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(newWordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 100, 40));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Difficulty", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        easy.setBackground(new java.awt.Color(255, 255, 255));
        difficultyGroup.add(easy);
        easy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        easy.setSelected(true);
        easy.setText("Easy");
        easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyMouseClicked(evt);
            }
        });
        jToolBar1.add(easy);

        medium.setBackground(new java.awt.Color(255, 255, 255));
        difficultyGroup.add(medium);
        medium.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        medium.setText("Medium");
        medium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediumMouseClicked(evt);
            }
        });
        jToolBar1.add(medium);

        hard.setBackground(new java.awt.Color(255, 255, 255));
        difficultyGroup.add(hard);
        hard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hard.setText("Hard");
        hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardMouseClicked(evt);
            }
        });
        jToolBar1.add(hard);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 130, 120));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Categories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        house.setBackground(new java.awt.Color(255, 255, 255));
        catagoriesGroup.add(house);
        house.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        house.setSelected(true);
        house.setText("Around the House");
        house.setFocusable(false);
        house.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        house.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                houseMouseClicked(evt);
            }
        });
        jToolBar2.add(house);

        movie.setBackground(new java.awt.Color(255, 255, 255));
        catagoriesGroup.add(movie);
        movie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movie.setText("Classic Movie");
        movie.setFocusable(false);
        movie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        movie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieMouseClicked(evt);
            }
        });
        jToolBar2.add(movie);

        fiction.setBackground(new java.awt.Color(255, 255, 255));
        catagoriesGroup.add(fiction);
        fiction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fiction.setText("Fictional Character");
        fiction.setFocusable(false);
        fiction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fiction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fictionMouseClicked(evt);
            }
        });
        jToolBar2.add(fiction);

        rhyme.setBackground(new java.awt.Color(255, 255, 255));
        catagoriesGroup.add(rhyme);
        rhyme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rhyme.setText("Rhyme");
        rhyme.setFocusable(false);
        rhyme.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rhyme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rhymeMouseClicked(evt);
            }
        });
        jToolBar2.add(rhyme);

        tv.setBackground(new java.awt.Color(255, 255, 255));
        catagoriesGroup.add(tv);
        tv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tv.setText("TV Shows");
        tv.setFocusable(false);
        tv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvMouseClicked(evt);
            }
        });
        jToolBar2.add(tv);

        jPanel1.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, -1, 180));

        jToolBar3.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Stats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jToolBar3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar3.setRollover(true);

        statsPane.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jToolBar3.add(statsPane);

        jPanel1.add(jToolBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 250, 80));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        aButton.setEnabled(false);
        updateWordDisplay('a', 'A');
    }//GEN-LAST:event_aButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        bButton.setEnabled(false);
        updateWordDisplay('b', 'B');
    }//GEN-LAST:event_bButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        cButton.setEnabled(false);
        updateWordDisplay('c', 'C');
    }//GEN-LAST:event_cButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        dButton.setEnabled(false);
        updateWordDisplay('d', 'D');
    }//GEN-LAST:event_dButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        eButton.setEnabled(false);
        updateWordDisplay('e', 'E');
    }//GEN-LAST:event_eButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        fButton.setEnabled(false);
        updateWordDisplay('f', 'F');
    }//GEN-LAST:event_fButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        gButton.setEnabled(false);
        updateWordDisplay('g', 'G');
    }//GEN-LAST:event_gButtonActionPerformed

    private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hButtonActionPerformed
        hButton.setEnabled(false);
        updateWordDisplay('h', 'H');
    }//GEN-LAST:event_hButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
        iButton.setEnabled(false);
        updateWordDisplay('i', 'I');
    }//GEN-LAST:event_iButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        jButton.setEnabled(false);
        updateWordDisplay('j', 'J');
    }//GEN-LAST:event_jButtonActionPerformed

    private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonActionPerformed
        kButton.setEnabled(false);
        updateWordDisplay('k', 'K');
    }//GEN-LAST:event_kButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        lButton.setEnabled(false);
        updateWordDisplay('l', 'L');
    }//GEN-LAST:event_lButtonActionPerformed

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        mButton.setEnabled(false);
        updateWordDisplay('m', 'M');
    }//GEN-LAST:event_mButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
        nButton.setEnabled(false);
        updateWordDisplay('n', 'N');
    }//GEN-LAST:event_nButtonActionPerformed

    private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oButtonActionPerformed
        oButton.setEnabled(false);
        updateWordDisplay('o', 'O');
    }//GEN-LAST:event_oButtonActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        pButton.setEnabled(false);
        updateWordDisplay('p', 'P');
    }//GEN-LAST:event_pButtonActionPerformed

    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
        qButton.setEnabled(false);
        updateWordDisplay('q', 'Q');
    }//GEN-LAST:event_qButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        rButton.setEnabled(false);
        updateWordDisplay('r', 'R');
    }//GEN-LAST:event_rButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        sButton.setEnabled(false);
        updateWordDisplay('s', 'S');
    }//GEN-LAST:event_sButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        tButton.setEnabled(false);
        updateWordDisplay('t', 'T');
    }//GEN-LAST:event_tButtonActionPerformed

    private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uButtonActionPerformed
        uButton.setEnabled(false);
        updateWordDisplay('u', 'U');
    }//GEN-LAST:event_uButtonActionPerformed

    private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonActionPerformed
        vButton.setEnabled(false);
        updateWordDisplay('v', 'V');
    }//GEN-LAST:event_vButtonActionPerformed

    private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wButtonActionPerformed
        wButton.setEnabled(false);
        updateWordDisplay('w', 'W');
    }//GEN-LAST:event_wButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
        xButton.setEnabled(false);
        updateWordDisplay('x', 'X');
    }//GEN-LAST:event_xButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButtonActionPerformed
        yButton.setEnabled(false);
        updateWordDisplay('y', 'Y');
    }//GEN-LAST:event_yButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zButtonActionPerformed
        zButton.setEnabled(false);
        updateWordDisplay('z', 'Z');
    }//GEN-LAST:event_zButtonActionPerformed

    private void newWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWordButtonActionPerformed
        setCursor(Cursor.WAIT_CURSOR);
        setWord(HangmanPhrase.convertStrToArrayList(HangmanPhrase.getPhrase(category, difficulty)));
        letterReset(true);
        imageReset();
        youLoseFrame.setVisible(false);
        winnerFrame.setVisible(false);

    }//GEN-LAST:event_newWordButtonActionPerformed

    private void easyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMouseClicked
        difficulty = "Easy";
    }//GEN-LAST:event_easyMouseClicked

    private void mediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumMouseClicked
        difficulty = "Medium";
    }//GEN-LAST:event_mediumMouseClicked

    private void hardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseClicked
        difficulty = "Hard";
    }//GEN-LAST:event_hardMouseClicked

    private void houseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_houseMouseClicked
        category = "Around the House";
    }//GEN-LAST:event_houseMouseClicked

    private void movieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieMouseClicked
        category = "Classic Movie";
    }//GEN-LAST:event_movieMouseClicked

    private void fictionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fictionMouseClicked
        category = "Fictional Character";
    }//GEN-LAST:event_fictionMouseClicked

    private void rhymeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rhymeMouseClicked
        category = "Rhyme";
    }//GEN-LAST:event_rhymeMouseClicked

    private void tvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvMouseClicked
        category = "TV Shows";
    }//GEN-LAST:event_tvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIApp().setVisible(true);
                }
            });

    }

    
    
    public void setWord(ArrayList<Character> word) {

        actualWord.clear();
        displayedWord.clear();
        actualWord.addAll(word);
        for (int i = 0; i <= word.size() - 1; i++) {
            char letter = actualWord.get(i);
            if (letter == ' ') {
                displayedWord.add(' ');
            }
            else
            displayedWord.add('_');
        }
        wordArea.setText(HangmanPhrase.convertStr(displayedWord));
        wordArea.setWrapStyleWord(true);
        statsPane.setText(score.getScore());

        setCursor(Cursor.DEFAULT_CURSOR);
    }

    public void updateWordDisplay(char letter, char capLetter) {
        int counter = 0;
        boolean wrong = false;
        boolean winFactor = false;
        for (Character c : actualWord) {
            if (c == letter) {
                displayedWord.set(counter, letter);
                winFactor = true;
                wrong = true;
                score.addCorrectGuess();
            }
            if (c == capLetter) {
                displayedWord.set(counter, capLetter);
                winFactor = true;
                wrong = true;
                score.addCorrectGuess();
            }
            counter++;
        }
        for (Character elt : displayedWord) {
            if (elt == '_') {
                winFactor = false;
            }
        }

        if (wrong == false) {
            if (coverHead.isVisible() == true) //reveals hanged man
            {
                coverHead.setVisible(false);
            } else if (coverBody.isVisible() == true) {
                coverBody.setVisible(false);
            } else if (coverLeftArm.isVisible() == true) {
                coverLeftArm.setVisible(false);
            } else if (coverRightArm.isVisible() == true) {
                coverRightArm.setVisible(false);
            } else if (coverLeftLeg.isVisible() == true) {
                coverLeftLeg.setVisible(false);
            } else if (coverRightLeg.isVisible() == true) {
                coverRightLeg.setVisible(false);
                loser();
                score.addLose();
            }
            score.addWrongGuess();
        }
        wordArea.setText(HangmanPhrase.convertStr(displayedWord));
        wordArea.setWrapStyleWord(true);
        if (winFactor == true) {
            winner();
            score.addWin();
        }
        statsPane.setText(score.getScore());
    }

    public void winner() {
        winnerFrame.setVisible(true);
        letterReset(false);
    }

    public void loser() {
        youLoseFrame.setVisible(true);
        letterReset(false);
        displayedWord.clear();
        displayedWord.addAll(actualWord);
    }

    public void imageReset() {
        coverHead.setVisible(true);
        coverBody.setVisible(true);
        coverLeftArm.setVisible(true);
        coverLeftLeg.setVisible(true);
        coverRightArm.setVisible(true);
        coverRightLeg.setVisible(true);
    }

    public void letterReset(boolean reset)//resets all the letter buttons
    {
        aButton.setEnabled(reset);
        bButton.setEnabled(reset);
        cButton.setEnabled(reset);
        dButton.setEnabled(reset);
        eButton.setEnabled(reset);
        fButton.setEnabled(reset);
        gButton.setEnabled(reset);
        hButton.setEnabled(reset);
        iButton.setEnabled(reset);
        jButton.setEnabled(reset);
        kButton.setEnabled(reset);
        lButton.setEnabled(reset);
        mButton.setEnabled(reset);
        nButton.setEnabled(reset);
        oButton.setEnabled(reset);
        pButton.setEnabled(reset);
        qButton.setEnabled(reset);
        rButton.setEnabled(reset);
        sButton.setEnabled(reset);
        tButton.setEnabled(reset);
        uButton.setEnabled(reset);
        vButton.setEnabled(reset);
        wButton.setEnabled(reset);
        xButton.setEnabled(reset);
        yButton.setEnabled(reset);
        zButton.setEnabled(reset);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.ButtonGroup catagoriesGroup;
    private javax.swing.JLabel coverBody;
    private javax.swing.JLabel coverHead;
    private javax.swing.JLabel coverLeftArm;
    private javax.swing.JLabel coverLeftLeg;
    private javax.swing.JLabel coverRightArm;
    private javax.swing.JLabel coverRightLeg;
    private javax.swing.JButton dButton;
    private javax.swing.ButtonGroup difficultyGroup;
    private javax.swing.JButton eButton;
    private javax.swing.JRadioButton easy;
    private javax.swing.JButton fButton;
    private javax.swing.JRadioButton fiction;
    private javax.swing.JButton gButton;
    private javax.swing.JButton hButton;
    private javax.swing.JLabel hangMan;
    private javax.swing.JRadioButton hard;
    private javax.swing.JRadioButton house;
    private javax.swing.JButton iButton;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JButton mButton;
    private javax.swing.JRadioButton medium;
    private javax.swing.JRadioButton movie;
    private javax.swing.JButton nButton;
    private javax.swing.JButton newWordButton;
    private javax.swing.JButton oButton;
    private javax.swing.JButton pButton;
    private javax.swing.JButton qButton;
    private javax.swing.JButton rButton;
    private javax.swing.JRadioButton rhyme;
    private javax.swing.JButton sButton;
    private javax.swing.JTextPane statsPane;
    private javax.swing.JButton tButton;
    private javax.swing.JRadioButton tv;
    private javax.swing.JButton uButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JInternalFrame winnerFrame;
    private javax.swing.JTextArea wordArea;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JInternalFrame youLoseFrame;
    private javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables
}
